#169817812 user signup on barefoot nomad
andela/blackninjas-frontend pull request #12
Opened 2020-02-07 06:21 UTC by VedaDom

#### What does this PR do?
- Users should be able Signup/Register to Barefoot Nomad.

#### Description of Task to be completed?
- Document code using JSDOC
- Under activity, endeavor to come up with the thought process (data flow) needed to implement this feature.
- Create a breakdown of steps as tasks under the task attribute below of PT.
- The sign up form should present to the user **descriptive** validation errors incase of any.
- The user should receive verification link on email upon successful registration.

#### How should this be manually tested?
After clone repository, go to the root of the project open path into command run the `npm install` and once setup is done click `npm start`, this will start a local server which will then automatically open your default browser, then navigate to `http://localhost:8080/auth/signup` and fill sign up form and click on sign up button.

#### What are the relevant pivotal tracker stories?
- [#169817812](https://www.pivotaltracker.com/story/show/169817812)

#### Screenshots (if appropriate)
<img width="1440" alt="Screen Shot 2020-02-07 at 08 16 26" src="https://user-images.githubusercontent.com/28502544/74005641-301cee80-4982-11ea-935f-b7dfae8a5d09.png">

2020-02-11 17:10 UTC, shemaeric1234 approved these changes

2020-02-12 10:32 UTC, mujohn26 approved these changes
Good Work @VedaDom

2020-02-14 04:06 UTC, Ruqoyah commented
Kindly fix the failing test on CI.

2020-02-18 10:52 UTC, bdushimi requested changes

2020-02-18 10:52 UTC, bdushimi commented on src/components/signup/signup_form.component.jsx
> +                                <Link style={{ textDecoration: 'none' }} href="https://blackninjas-backend-staging.herokuapp.com/api/v1/auth/facebook">
@VedaDom kindly use the env variables here too.

2020-02-18 10:52 UTC, bdushimi commented on src/components/signup/signup_form.component.jsx
> +                                <Link style={{ textDecoration: 'none' }} href="https://blackninjas-backend-staging.herokuapp.com/api/v1/auth/google">
@VedaDom kindly use env. variables here too

2020-02-18 11:57 UTC, bdushimi approved these changes

2020-02-18 11:58 UTC, merged